name: quran_i_kerim
description: Kur’an-ı Kerim, sesli Kuran, mealler ve okuma planları için hafif ve modern Flutter uygulaması.
publish_to: "none"
version: 0.4.0+4

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  adhan_dart: ^2.0.1
  audio_service: ^0.18.19
  just_audio: ^0.10.6
  quran: ^1.4.1
  shared_preferences: ^2.5.3
  timezone: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/translations/tr_rwwad.json.gz
