import Flutter
import UIKit
import UniformTypeIdentifiers
import UserNotifications

@main
@objc class AppDelegate: FlutterAppDelegate {
  private let audioSessionCoordinator = AudioSessionCoordinator.shared
  private var backupExclusionChannel: BackupExclusionChannel?, nowPlayingChannel: NowPlayingChannel?, audioLifecycleChannel: AudioLifecycleChannel?, notificationPermissionChannel: NotificationPermissionChannel?, locationHeadingChannel: LocationHeadingChannel?, documentHandoffChannel: DocumentHandoffChannel?, widgetSnapshotChannel: WidgetSnapshotChannel?, nativeLifecycleStateChannel: NativeLifecycleStateChannel?, microphoneRecordingChannel: MicrophoneRecordingChannel?, nativeShareChannel: NativeShareChannel?, deepLinkChannel: DeepLinkChannel?
  override func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool { audioSessionCoordinator.start(); GeneratedPluginRegistrant.register(with: self); UNUserNotificationCenter.current().delegate = self; configureNativeChannels(); if let url = launchOptions?[.url] as? URL { _ = deepLinkChannel?.receive(url) }; return super.application(application, didFinishLaunchingWithOptions: launchOptions) }
  override func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Bool { let accepted = deepLinkChannel?.receive(url) ?? false; return super.application(app, open: url, options: options) || accepted }
  override func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) { if notification.request.identifier == NotificationPermissionChannel.selfTestIdentifier { completionHandler([.banner, .sound]); return }; super.userNotificationCenter(center, willPresent: notification, withCompletionHandler: completionHandler) }
  override func applicationWillTerminate(_ application: UIApplication) { deepLinkChannel?.detach(); nativeShareChannel?.detach(); microphoneRecordingChannel?.detach(); nativeLifecycleStateChannel?.markCleanTermination(); nativeLifecycleStateChannel?.detach(); widgetSnapshotChannel?.detach(); documentHandoffChannel?.detach(); locationHeadingChannel?.detach(); notificationPermissionChannel?.detach(); audioLifecycleChannel?.detach(); nowPlayingChannel?.detach(); backupExclusionChannel?.detach(); audioSessionCoordinator.stop(); super.applicationWillTerminate(application) }
  private func configureNativeChannels() { guard let controller = window?.rootViewController as? FlutterViewController else { NSLog("Unable to install native channels: Flutter view controller unavailable."); return }; let messenger = controller.binaryMessenger; backupExclusionChannel = BackupExclusionChannel(binaryMessenger: messenger); nowPlayingChannel = NowPlayingChannel(binaryMessenger: messenger); audioLifecycleChannel = AudioLifecycleChannel(binaryMessenger: messenger); notificationPermissionChannel = NotificationPermissionChannel(binaryMessenger: messenger); locationHeadingChannel = LocationHeadingChannel(binaryMessenger: messenger); documentHandoffChannel = DocumentHandoffChannel(binaryMessenger: messenger, presenter: controller); widgetSnapshotChannel = WidgetSnapshotChannel(binaryMessenger: messenger); nativeLifecycleStateChannel = NativeLifecycleStateChannel(binaryMessenger: messenger); microphoneRecordingChannel = MicrophoneRecordingChannel(binaryMessenger: messenger); nativeShareChannel = NativeShareChannel(binaryMessenger: messenger, presenter: controller); deepLinkChannel = DeepLinkChannel(binaryMessenger: messenger) }
}

final class DeepLinkChannel {
  static let channelName = "app.quranikerim/native_deep_link"; private let channel: FlutterMethodChannel; private var pending: [String] = []; private let maxPending = 8
  init(binaryMessenger: FlutterBinaryMessenger) { channel = FlutterMethodChannel(name: Self.channelName, binaryMessenger: binaryMessenger); channel.setMethodCallHandler { [weak self] call, result in self?.handle(call, result: result) } }
  @discardableResult func receive(_ url: URL) -> Bool { guard let normalized = normalizedURLString(url) else { return false }; if pending.last != normalized { pending.append(normalized); if pending.count > maxPending { pending.removeFirst(pending.count - maxPending) } }; channel.invokeMethod("linkReceived", arguments: ["url": normalized]); return true }
  func detach() { channel.setMethodCallHandler(nil); pending.removeAll() }
  private func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) { switch call.method { case "capabilities": result(["customScheme": true, "universalLink": false, "coldStartBuffer": true, "maxPending": maxPending]); case "pendingLinks": result(pending); case "consumePendingLinks": let links = pending; pending.removeAll(); result(links); case "clearPendingLinks": pending.removeAll(); result(nil); default: result(FlutterMethodNotImplemented) } }
  private func normalizedURLString(_ url: URL) -> String? { guard url.scheme?.lowercased() == "quranikerim", var components = URLComponents(url: url, resolvingAgainstBaseURL: false) else { return nil }; components.scheme = "quranikerim"; components.host = components.host?.lowercased(); guard components.host == "prayer" || components.host == "reader" || components.host == "hifz" else { return nil }; return components.url?.absoluteString }
}

final class DocumentHandoffChannel: NSObject, UIDocumentPickerDelegate {
  private static let channelName = "app.quranikerim/native_document_handoff", maxImportBytes: Int64 = 64 * 1024 * 1024, maxExportBytes: Int64 = 64 * 1024 * 1024
  private static let exportDirectoryName = "quran-user-exports", orphanLifetime: TimeInterval = 24 * 60 * 60
  private let channel: FlutterMethodChannel; private weak var presenter: UIViewController?; private var pendingResult: FlutterResult?; private var temporaryExportURL: URL?
  init(binaryMessenger: FlutterBinaryMessenger, presenter: UIViewController) { channel = FlutterMethodChannel(name: Self.channelName, binaryMessenger: binaryMessenger); self.presenter = presenter; super.init(); cleanupOrphanedExports(); channel.setMethodCallHandler { [weak self] call, result in self?.handle(call, result: result) } }
  func detach() { finish(nil); channel.setMethodCallHandler(nil) }
  private func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) { guard pendingResult == nil else { result(FlutterError(code: "busy", message: "A document handoff is already active.", details: nil)); return }; switch call.method { case "exportFile": exportFile(call.arguments, result: result); case "importFile": importFile(result: result); case "deleteImportedFile": deleteImportedFile(call.arguments, result: result); case "capabilities": result(["files": true, "icloudDrive": true, "securityScopedImport": true, "copyOnImport": true, "maxImportBytes": Self.maxImportBytes, "maxExportBytes": Self.maxExportBytes, "fileProtection": true, "explicitImportCleanup": true, "activePresenterResolution": true, "activeSceneAware": true, "originatingScenePreferred": true, "isolatedExportSession": true, "orphanExportCleanup": true]); default: result(FlutterMethodNotImplemented) } }
  private func exportFile(_ arguments: Any?, result: @escaping FlutterResult) {
    guard let args = arguments as? [String: Any], let sourcePath = args["path"] as? String, !sourcePath.isEmpty else { result(FlutterError(code: "invalid_arguments", message: "exportFile requires a non-empty path.", details: nil)); return }; let source = URL(fileURLWithPath: sourcePath).standardizedFileURL
    do { let sourceValues = try source.resourceValues(forKeys: [.isRegularFileKey, .fileSizeKey]); guard sourceValues.isRegularFile == true else { result(FlutterError(code: "missing_file", message: "The export source is not a regular file.", details: nil)); return }; let sourceSize = Int64(sourceValues.fileSize ?? 0); guard sourceSize >= 0 && sourceSize <= Self.maxExportBytes else { result(FlutterError(code: "export_too_large", message: "The export exceeds the 64 MB portable-backup limit.", details: ["maxBytes": Self.maxExportBytes, "size": sourceSize])); return }; guard let presenter = activePresenter(), presenter.viewIfLoaded?.window != nil else { result(FlutterError(code: "no_presenter", message: "No active iOS scene is available.", details: nil)); return }; cleanupOrphanedExports(); let root = exportRootDirectory(); try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true); try protectAndExcludeFromBackup(root); let session = root.appendingPathComponent(UUID().uuidString.lowercased(), isDirectory: true); try FileManager.default.createDirectory(at: session, withIntermediateDirectories: true); try protectAndExcludeFromBackup(session); let preferredName = sanitizedFilename(args["filename"] as? String) ?? sanitizedFilename(source.lastPathComponent) ?? "quran-backup.dat", staged = session.appendingPathComponent(preferredName, isDirectory: false); do { try FileManager.default.copyItem(at: source, to: staged); try protectAndExcludeFromBackup(staged) } catch { try? FileManager.default.removeItem(at: session); throw error }; temporaryExportURL = staged; pendingResult = result; let picker = UIDocumentPickerViewController(forExporting: [staged], asCopy: true); picker.delegate = self; picker.modalPresentationStyle = .formSheet; presenter.present(picker, animated: true) } catch { cleanupExport(); result(FlutterError(code: "export_failed", message: error.localizedDescription, details: nil)) }
  }
  private func importFile(result: @escaping FlutterResult) { guard let presenter = activePresenter(), presenter.viewIfLoaded?.window != nil else { result(FlutterError(code: "no_presenter", message: "No active iOS scene is available.", details: nil)); return }; pendingResult = result; let picker = UIDocumentPickerViewController(forOpeningContentTypes: [.data], asCopy: true); picker.allowsMultipleSelection = false; picker.delegate = self; picker.modalPresentationStyle = .formSheet; presenter.present(picker, animated: true) }
  private func deleteImportedFile(_ arguments: Any?, result: @escaping FlutterResult) { guard let args = arguments as? [String: Any], let rawPath = args["path"] as? String, !rawPath.isEmpty else { result(FlutterError(code: "invalid_arguments", message: "deleteImportedFile requires a path.", details: nil)); return }; do { let directory = try importDirectory().standardizedFileURL, target = URL(fileURLWithPath: rawPath).standardizedFileURL; guard target.deletingLastPathComponent() == directory else { result(FlutterError(code: "invalid_import_path", message: "Only files created by the import handoff can be deleted.", details: nil)); return }; if FileManager.default.fileExists(atPath: target.path) { try FileManager.default.removeItem(at: target) }; result(["deleted": true]) } catch { result(FlutterError(code: "import_cleanup_failed", message: error.localizedDescription, details: nil)) } }
  func documentPickerWasCancelled(_ controller: UIDocumentPickerViewController) { finish(["status": "cancelled"]) }
  func documentPicker(_ controller: UIDocumentPickerViewController, didPickDocumentsAt urls: [URL]) { guard let picked = urls.first else { finish(["status": "cancelled"]); return }; let scoped = picked.startAccessingSecurityScopedResource(); defer { if scoped { picked.stopAccessingSecurityScopedResource() } }; do { let sourceValues = try picked.resourceValues(forKeys: [.isRegularFileKey, .fileSizeKey]); guard sourceValues.isRegularFile == true else { finish(error: FlutterError(code: "import_not_file", message: "The selected item is not a regular file.", details: nil)); return }; let sourceSize = Int64(sourceValues.fileSize ?? 0); guard sourceSize >= 0 && sourceSize <= Self.maxImportBytes else { finish(error: FlutterError(code: "import_too_large", message: "The selected backup exceeds the 64 MB portable-backup limit.", details: ["maxBytes": Self.maxImportBytes, "size": sourceSize])); return }; let inbox = try importDirectory(), destination = uniqueDestination(in: inbox, filename: sanitizedFilename(picked.lastPathComponent) ?? "import.quranbackup"); try FileManager.default.copyItem(at: picked, to: destination); try protectAndExcludeFromBackup(destination); let attributes = try FileManager.default.attributesOfItem(atPath: destination.path), size = (attributes[.size] as? NSNumber)?.int64Value ?? 0; guard size <= Self.maxImportBytes else { try? FileManager.default.removeItem(at: destination); finish(error: FlutterError(code: "import_too_large", message: "The copied backup exceeds the 64 MB portable-backup limit.", details: ["maxBytes": Self.maxImportBytes, "size": size])); return }; finish(["status": "selected", "path": destination.path, "filename": destination.lastPathComponent, "size": size]) } catch { finish(error: FlutterError(code: "import_failed", message: error.localizedDescription, details: nil)) } }
  private func activePresenter() -> UIViewController? { if let presenter, let scene = presenter.viewIfLoaded?.window?.windowScene, scene.activationState == .foregroundActive { return topPresenter(from: presenter) }; let scenes = UIApplication.shared.connectedScenes.compactMap { $0 as? UIWindowScene }.filter { $0.activationState == .foregroundActive }; for scene in scenes { if let root = scene.windows.first(where: { $0.isKeyWindow })?.rootViewController { return topPresenter(from: root) } }; guard let presenter else { return nil }; return topPresenter(from: presenter) }
  private func topPresenter(from controller: UIViewController) -> UIViewController { if let presented = controller.presentedViewController, !presented.isBeingDismissed { return topPresenter(from: presented) }; if let navigation = controller as? UINavigationController, let visible = navigation.visibleViewController { return topPresenter(from: visible) }; if let tab = controller as? UITabBarController, let selected = tab.selectedViewController { return topPresenter(from: selected) }; if let split = controller as? UISplitViewController, let last = split.viewControllers.last { return topPresenter(from: last) }; return controller }
  private func exportRootDirectory() -> URL { FileManager.default.temporaryDirectory.appendingPathComponent(Self.exportDirectoryName, isDirectory: true) }
  private func cleanupOrphanedExports(now: Date = Date()) { let root = exportRootDirectory(); guard let sessions = try? FileManager.default.contentsOfDirectory(at: root, includingPropertiesForKeys: [.contentModificationDateKey, .isDirectoryKey], options: [.skipsHiddenFiles]) else { return }; let active = temporaryExportURL?.deletingLastPathComponent().standardizedFileURL; for session in sessions { guard session.standardizedFileURL != active, let values = try? session.resourceValues(forKeys: [.contentModificationDateKey, .isDirectoryKey]), values.isDirectory == true, let modified = values.contentModificationDate, now.timeIntervalSince(modified) >= Self.orphanLifetime else { continue }; try? FileManager.default.removeItem(at: session) } }
  private func importDirectory() throws -> URL { let base = try FileManager.default.url(for: .applicationSupportDirectory, in: .userDomainMask, appropriateFor: nil, create: true), directory = base.appendingPathComponent("ImportedUserBackups", isDirectory: true); try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true); try protectAndExcludeFromBackup(directory); return directory }
  private func protectAndExcludeFromBackup(_ url: URL) throws { try FileManager.default.setAttributes([.protectionKey: FileProtectionType.completeUntilFirstUserAuthentication], ofItemAtPath: url.path); var values = URLResourceValues(); values.isExcludedFromBackup = true; var mutable = url; try mutable.setResourceValues(values) }
  private func uniqueDestination(in directory: URL, filename: String) -> URL { let base = URL(fileURLWithPath: filename).deletingPathExtension().lastPathComponent, ext = URL(fileURLWithPath: filename).pathExtension; var candidate = directory.appendingPathComponent(filename), index = 2; while FileManager.default.fileExists(atPath: candidate.path) { candidate = directory.appendingPathComponent(ext.isEmpty ? "\(base)-\(index)" : "\(base)-\(index).\(ext)"); index += 1 }; return candidate }
  private func sanitizedFilename(_ value: String?) -> String? { guard let value else { return nil }; let leaf = URL(fileURLWithPath: value).lastPathComponent.trimmingCharacters(in: .whitespacesAndNewlines); return (!leaf.isEmpty && leaf != "." && leaf != "..") ? leaf : nil }
  private func finish(_ payload: Any?) { guard let result = pendingResult else { cleanupExport(); return }; pendingResult = nil; cleanupExport(); result(payload) }
  private func finish(error: FlutterError) { guard let result = pendingResult else { cleanupExport(); return }; pendingResult = nil; cleanupExport(); result(error) }
  private func cleanupExport() { if let temporaryExportURL { try? FileManager.default.removeItem(at: temporaryExportURL.deletingLastPathComponent()) }; temporaryExportURL = nil }
}
