const Map<String, Map<String, String>> qadaFastingArchiveStrings = {
  'tr': {
    'title': 'Kaza defteri yedeği', 'localTitle': 'Bu cihazdaki defter', 'records': 'Kayıt', 'remaining': 'Kalan gün', 'includeNotes': 'Özel notları yedeğe ekle', 'includeNotesWarning': 'Kapalı tutarsan hassas notlar dışarı çıkmaz.', 'export': 'Taşınabilir yedek oluştur', 'exportTitle': 'Kaza defteri yedeği', 'exportFailed': 'Yedek oluşturulamadı.', 'pasteImport': 'Panodan yedek içe aktar', 'pasteHelp': 'İçe aktarmadan önce yedeğin JSON metnini panoya kopyala. Uygulama önce önizleme gösterir; hiçbir kayıt sessizce değiştirilmez.', 'clipboardEmpty': 'Panoda içe aktarılabilecek metin yok.', 'invalidArchive': 'Bu metin geçerli bir kaza defteri yedeği değil.', 'previewTitle': 'Yedeği kontrol et', 'incoming': 'Yedekteki kayıt', 'newRecords': 'Yeni kayıt', 'duplicates': 'Zaten mevcut', 'conflictingRecords': 'Çakışan kayıt', 'archiveBalance': 'Yedekte kalan gün', 'containsNotes': 'Bu yedek özel notlar içeriyor.', 'mergeBlocked': 'Aynı kimliğe sahip farklı kayıtlar var. Veri kaybını önlemek için Birleştir kapatıldı.', 'mergeExplanation': 'Birleştir yerel kayıtları korur ve yalnız yeni kayıtları ekler.', 'replaceWarning': 'Değiştir bu cihazdaki kaza defterinin tamamını yedekteki kayıtlarla değiştirir.', 'merge': 'Birleştir', 'replace': 'Değiştir', 'cancel': 'İptal', 'replaceConfirmTitle': 'Yerel defteri değiştir?', 'replaceConfirmBody': 'Bu işlem mevcut yerel kaza kayıtlarını yedekteki kayıtlarla değiştirecek. Yanlışlıkla veri kaybını önlemek için yalnız gerçekten istediğinde devam et.', 'restoreComplete': 'Kaza defteri geri yüklendi.', 'conflict': 'Yedek ile yerel geçmiş çakışıyor; hiçbir kayıt değiştirilmedi.'
  },
  'en': {
    'title': 'Qada ledger backup', 'localTitle': 'Ledger on this device', 'records': 'Records', 'remaining': 'Remaining days', 'includeNotes': 'Include private notes', 'includeNotesWarning': 'Keep this off to leave sensitive notes out of the archive.', 'export': 'Create portable backup', 'exportTitle': 'Qada ledger backup', 'exportFailed': 'The backup could not be created.', 'pasteImport': 'Import backup from clipboard', 'pasteHelp': 'Copy the backup JSON text to the clipboard first. The app always previews it before changing any record.', 'clipboardEmpty': 'There is no importable text on the clipboard.', 'invalidArchive': 'This text is not a valid qada ledger backup.', 'previewTitle': 'Review backup', 'incoming': 'Records in backup', 'newRecords': 'New records', 'duplicates': 'Already present', 'conflictingRecords': 'Conflicting records', 'archiveBalance': 'Remaining days in backup', 'containsNotes': 'This backup contains private notes.', 'mergeBlocked': 'Different records use the same id. Merge is disabled to prevent silent data loss.', 'mergeExplanation': 'Merge preserves local history and adds only new records.', 'replaceWarning': 'Replace swaps the entire local qada ledger for the backup.', 'merge': 'Merge', 'replace': 'Replace', 'cancel': 'Cancel', 'replaceConfirmTitle': 'Replace local ledger?', 'replaceConfirmBody': 'This replaces the qada history on this device with the backup. Continue only if that is what you intend.', 'restoreComplete': 'Qada ledger restored.', 'conflict': 'The backup conflicts with local history; no records were changed.'
  },
  'fr': {
    'title': 'Sauvegarde des jeûnes à rattraper', 'localTitle': 'Registre sur cet appareil', 'records': 'Entrées', 'remaining': 'Jours restants', 'includeNotes': 'Inclure les notes privées', 'includeNotesWarning': 'Laissez désactivé pour exclure les notes sensibles.', 'export': 'Créer une sauvegarde portable', 'exportTitle': 'Sauvegarde du registre', 'exportFailed': 'Impossible de créer la sauvegarde.', 'pasteImport': 'Importer depuis le presse-papiers', 'pasteHelp': 'Copiez d’abord le texte JSON de la sauvegarde. Un aperçu est toujours affiché avant toute modification.', 'clipboardEmpty': 'Aucun texte importable dans le presse-papiers.', 'invalidArchive': 'Ce texte n’est pas une sauvegarde valide.', 'previewTitle': 'Vérifier la sauvegarde', 'incoming': 'Entrées dans la sauvegarde', 'newRecords': 'Nouvelles entrées', 'duplicates': 'Déjà présentes', 'conflictingRecords': 'Entrées en conflit', 'archiveBalance': 'Jours restants dans la sauvegarde', 'containsNotes': 'Cette sauvegarde contient des notes privées.', 'mergeBlocked': 'Des entrées différentes utilisent le même identifiant. La fusion est désactivée pour éviter une perte silencieuse.', 'mergeExplanation': 'Fusionner conserve les données locales et ajoute uniquement les nouvelles entrées.', 'replaceWarning': 'Remplacer substitue tout le registre local par la sauvegarde.', 'merge': 'Fusionner', 'replace': 'Remplacer', 'cancel': 'Annuler', 'replaceConfirmTitle': 'Remplacer le registre local ?', 'replaceConfirmBody': 'Cette action remplace l’historique local par la sauvegarde.', 'restoreComplete': 'Registre restauré.', 'conflict': 'Conflit avec l’historique local ; aucune donnée n’a été modifiée.'
  },
  'ar': {
    'title': 'نسخة سجل القضاء', 'localTitle': 'السجل على هذا الجهاز', 'records': 'السجلات', 'remaining': 'الأيام المتبقية', 'includeNotes': 'تضمين الملاحظات الخاصة', 'includeNotesWarning': 'اتركه معطلاً لاستبعاد الملاحظات الحساسة من النسخة.', 'export': 'إنشاء نسخة محمولة', 'exportTitle': 'نسخة سجل القضاء', 'exportFailed': 'تعذر إنشاء النسخة الاحتياطية.', 'pasteImport': 'استيراد نسخة من الحافظة', 'pasteHelp': 'انسخ نص JSON للنسخة إلى الحافظة أولاً. يعرض التطبيق معاينة قبل تغيير أي سجل.', 'clipboardEmpty': 'لا يوجد نص صالح للاستيراد في الحافظة.', 'invalidArchive': 'هذا النص ليس نسخة صالحة لسجل القضاء.', 'previewTitle': 'مراجعة النسخة', 'incoming': 'السجلات في النسخة', 'newRecords': 'سجلات جديدة', 'duplicates': 'موجودة بالفعل', 'conflictingRecords': 'سجلات متعارضة', 'archiveBalance': 'الأيام المتبقية في النسخة', 'containsNotes': 'تحتوي هذه النسخة على ملاحظات خاصة.', 'mergeBlocked': 'توجد سجلات مختلفة تحمل المعرّف نفسه. تم تعطيل الدمج لمنع فقدان البيانات بصمت.', 'mergeExplanation': 'يحافظ الدمج على السجل المحلي ويضيف السجلات الجديدة فقط.', 'replaceWarning': 'يستبدل خيار الاستبدال سجل القضاء المحلي بالكامل بمحتوى النسخة.', 'merge': 'دمج', 'replace': 'استبدال', 'cancel': 'إلغاء', 'replaceConfirmTitle': 'استبدال السجل المحلي؟', 'replaceConfirmBody': 'سيتم استبدال سجل القضاء على هذا الجهاز بالنسخة الاحتياطية. تابع فقط إذا كان هذا ما تريده.', 'restoreComplete': 'تمت استعادة سجل القضاء.', 'conflict': 'تتعارض النسخة مع السجل المحلي؛ لم يتم تغيير أي سجل.'
  },
  'az': {
    'title': 'Qəza dəftəri yedəyi', 'localTitle': 'Bu cihazdakı dəftər', 'records': 'Qeydlər', 'remaining': 'Qalan günlər', 'includeNotes': 'Məxfi qeydləri yedəyə daxil et', 'includeNotesWarning': 'Həssas qeydləri yedəkdən kənarda saxlamaq üçün bunu söndürülmüş saxla.', 'export': 'Daşına bilən yedək yarat', 'exportTitle': 'Qəza dəftəri yedəyi', 'exportFailed': 'Yedək yaradıla bilmədi.', 'pasteImport': 'Yedəyi mübadilə buferindən idxal et', 'pasteHelp': 'Əvvəlcə yedəyin JSON mətnini mübadilə buferinə köçür. Tətbiq hər hansı qeydi dəyişməzdən əvvəl önizləmə göstərir.', 'clipboardEmpty': 'Mübadilə buferində idxal edilə bilən mətn yoxdur.', 'invalidArchive': 'Bu mətn etibarlı qəza dəftəri yedəyi deyil.', 'previewTitle': 'Yedəyi yoxla', 'incoming': 'Yedəkdəki qeydlər', 'newRecords': 'Yeni qeydlər', 'duplicates': 'Artıq mövcuddur', 'conflictingRecords': 'Ziddiyyətli qeydlər', 'archiveBalance': 'Yedəkdə qalan günlər', 'containsNotes': 'Bu yedək məxfi qeydlər ehtiva edir.', 'mergeBlocked': 'Fərqli qeydlər eyni kimlikdən istifadə edir. Səssiz məlumat itkisinin qarşısını almaq üçün birləşdirmə söndürülüb.', 'mergeExplanation': 'Birləşdirmə yerli tarixçəni qoruyur və yalnız yeni qeydləri əlavə edir.', 'replaceWarning': 'Əvəz etmə yerli qəza dəftərini tamamilə yedəklə dəyişir.', 'merge': 'Birləşdir', 'replace': 'Əvəz et', 'cancel': 'Ləğv et', 'replaceConfirmTitle': 'Yerli dəftər əvəz edilsin?', 'replaceConfirmBody': 'Bu cihazdakı qəza tarixçəsi yedəklə əvəz ediləcək. Yalnız bunu həqiqətən istəyirsənsə davam et.', 'restoreComplete': 'Qəza dəftəri bərpa edildi.', 'conflict': 'Yedək yerli tarixçə ilə ziddiyyət təşkil edir; heç bir qeyd dəyişdirilmədi.'
  },
  'ru': {
    'title': 'Резервная копия када', 'localTitle': 'Учёт на этом устройстве', 'records': 'Записи', 'remaining': 'Осталось дней', 'includeNotes': 'Включить личные заметки', 'includeNotesWarning': 'Оставьте выключенным, чтобы чувствительные заметки не попадали в копию.', 'export': 'Создать переносимую копию', 'exportTitle': 'Резервная копия када', 'exportFailed': 'Не удалось создать резервную копию.', 'pasteImport': 'Импортировать из буфера обмена', 'pasteHelp': 'Сначала скопируйте JSON-текст резервной копии. Приложение всегда показывает предварительный просмотр до изменения записей.', 'clipboardEmpty': 'В буфере обмена нет текста для импорта.', 'invalidArchive': 'Этот текст не является допустимой копией журнала када.', 'previewTitle': 'Проверить копию', 'incoming': 'Записей в копии', 'newRecords': 'Новые записи', 'duplicates': 'Уже есть', 'conflictingRecords': 'Конфликтующие записи', 'archiveBalance': 'Осталось дней в копии', 'containsNotes': 'Эта копия содержит личные заметки.', 'mergeBlocked': 'Разные записи используют один идентификатор. Объединение отключено, чтобы избежать скрытой потери данных.', 'mergeExplanation': 'Объединение сохраняет локальную историю и добавляет только новые записи.', 'replaceWarning': 'Замена полностью заменит локальный журнал када содержимым копии.', 'merge': 'Объединить', 'replace': 'Заменить', 'cancel': 'Отмена', 'replaceConfirmTitle': 'Заменить локальный журнал?', 'replaceConfirmBody': 'История када на этом устройстве будет заменена резервной копией. Продолжайте только если это действительно нужно.', 'restoreComplete': 'Журнал када восстановлен.', 'conflict': 'Копия конфликтует с локальной историей; записи не изменены.'
  },
};

String qadaFastingArchiveText(String languageCode, String key) =>
    qadaFastingArchiveStrings[languageCode]?[key] ??
    qadaFastingArchiveStrings['en']![key] ??
    key;
