import 'package:flutter/widgets.dart';

class PrayerNotificationSelfTestStrings {
  const PrayerNotificationSelfTestStrings({required this.send, required this.sent, required this.denied, required this.failed, required this.confirmPrompt, required this.received, required this.notReceived, required this.receivedAck, required this.notReceivedHelp});
  final String send, sent, denied, failed, confirmPrompt, received, notReceived, receivedAck, notReceivedHelp;
}

PrayerNotificationSelfTestStrings prayerNotificationSelfTestStrings(BuildContext context) {
  final language = Localizations.localeOf(context).languageCode;
  return switch (language) {
    'tr' => const PrayerNotificationSelfTestStrings(send: 'Test bildirimi gönder', sent: 'Test bildirimi gönderildi.', denied: 'Bildirim izni kapalı.', failed: 'Test bildirimi gönderilemedi.', confirmPrompt: 'Bildirimi gerçekten gördünüz veya duydunuz mu?', received: 'Evet, geldi', notReceived: 'Hayır, gelmedi', receivedAck: 'Bildirim yolu çalışıyor.', notReceivedHelp: 'Bildirim ulaşmadı. Yukarıdaki izin ve sistem tanılarını kontrol edin.'),
    'ar' => const PrayerNotificationSelfTestStrings(send: 'إرسال إشعار تجريبي', sent: 'تم إرسال الإشعار التجريبي.', denied: 'إذن الإشعارات متوقف.', failed: 'تعذر إرسال الإشعار التجريبي.', confirmPrompt: 'هل رأيت الإشعار أو سمعته بالفعل؟', received: 'نعم، وصل', notReceived: 'لا، لم يصل', receivedAck: 'مسار الإشعارات يعمل.', notReceivedHelp: 'لم يصل الإشعار. تحقق من الأذونات وتشخيصات النظام أعلاه.'),
    'az' => const PrayerNotificationSelfTestStrings(send: 'Test bildirişi göndər', sent: 'Test bildirişi göndərildi.', denied: 'Bildiriş icazəsi bağlıdır.', failed: 'Test bildirişi göndərilə bilmədi.', confirmPrompt: 'Bildirişi həqiqətən gördünüz və ya eşitdiniz?', received: 'Bəli, gəldi', notReceived: 'Xeyr, gəlmədi', receivedAck: 'Bildiriş yolu işləyir.', notReceivedHelp: 'Bildiriş çatmadı. Yuxarıdakı icazə və sistem diaqnostikasını yoxlayın.'),
    'ru' => const PrayerNotificationSelfTestStrings(send: 'Отправить тестовое уведомление', sent: 'Тестовое уведомление отправлено.', denied: 'Разрешение на уведомления отключено.', failed: 'Не удалось отправить тестовое уведомление.', confirmPrompt: 'Вы действительно увидели или услышали уведомление?', received: 'Да, пришло', notReceived: 'Нет, не пришло', receivedAck: 'Канал уведомлений работает.', notReceivedHelp: 'Уведомление не пришло. Проверьте разрешения и системную диагностику выше.'),
    'fr' => const PrayerNotificationSelfTestStrings(send: 'Envoyer une notification test', sent: 'Notification test envoyée.', denied: 'Les notifications ne sont pas autorisées.', failed: 'Impossible d’envoyer la notification test.', confirmPrompt: 'Avez-vous réellement vu ou entendu la notification ?', received: 'Oui, reçue', notReceived: 'Non, rien reçu', receivedAck: 'Le circuit de notification fonctionne.', notReceivedHelp: 'La notification n’est pas arrivée. Vérifiez les autorisations et diagnostics système ci-dessus.'),
    _ => const PrayerNotificationSelfTestStrings(send: 'Send test notification', sent: 'Test notification sent.', denied: 'Notification permission is off.', failed: 'Could not send the test notification.', confirmPrompt: 'Did you actually see or hear the notification?', received: 'Yes, it arrived', notReceived: 'No, it did not', receivedAck: 'The notification path is working.', notReceivedHelp: 'The notification did not arrive. Check the permission and system diagnostics above.'),
  };
}